version: '3.7'

services:

  redis:
    image: redis:7.2-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: --port ${REDIS_PORT}
    restart: always
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:${WEB_PORT}
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    env_file:
      - .env
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
    env_file:
      - .env
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    restart: always