# Generated by Django 5.1.5 on 2025-02-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usermanagement'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_management_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_management_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
